/** Content-only foreground transport. No runtime, plugin, filesystem, or provider dependencies. */
export const MANAGED_ASK_MODEL = "gpt-5.6-luna";
export const MANAGED_ASK_PROVIDER = "openai";
export const MANAGED_ASK_DISCLOSURE = "Send this meeting's transcript, question, and conversation history to Meetless and OpenAI to answer? Audio is not sent. Your recordings, transcript, and chat stay on your Mac. Meetless does not persist Ask content on the backend. OpenAI abuse monitoring may retain content for up to 30 days, or longer for legal or safety exceptions. OpenAI may also retain encrypted prompt-cache data for up to 24 hours. This is not zero data retention. Each Ask or retry sends a new request.";

export interface ManagedAskRequest {
  attemptId: string;
  consent: true;
  segments: Array<{ segmentId: string; text: string }>;
  messages: Array<{ role: "user" | "assistant"; text: string }>;
}
export type ManagedAskAnswer =
  | { outcome: "supported"; text: string; citationSegmentIds: string[] }
  | { outcome: "insufficient_evidence"; text: null; citationSegmentIds: [] };

function invalid(): never { throw new Error("Managed Ask data is invalid."); }
function object(value: unknown, keys: string[]): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) return invalid();
  const record = value as Record<string, unknown>;
  if (Object.keys(record).length !== keys.length || keys.some((key) => !Object.hasOwn(record, key))) return invalid();
  return record;
}
function nonempty(value: unknown): string {
  if (typeof value !== "string" || !value.trim()) return invalid();
  return value;
}
export function requireManagedAskConsent(consent: unknown): asserts consent is true {
  if (consent !== true) throw new Error("Confirm sending this meeting's transcript and conversation to OpenAI before Ask or retry.");
}
export function parseManagedAskRequest(value: unknown): ManagedAskRequest {
  const data = object(value, ["attemptId", "consent", "segments", "messages"]);
  requireManagedAskConsent(data.consent);
  // Attempt identity is generated by the local store, not free-form content metadata.
  const attemptId = nonempty(data.attemptId);
  if (!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/iu.test(attemptId)) return invalid();
  if (!Array.isArray(data.segments) || !data.segments.length || !Array.isArray(data.messages) || !data.messages.length) return invalid();
  const segments = data.segments.map((value) => {
    const segment = object(value, ["segmentId", "text"]);
    return { segmentId: nonempty(segment.segmentId), text: nonempty(segment.text) };
  });
  if (new Set(segments.map((segment) => segment.segmentId)).size !== segments.length) return invalid();
  const messages = data.messages.map((value): ManagedAskRequest["messages"][number] => {
    const message = object(value, ["role", "text"]);
    if (message.role !== "user" && message.role !== "assistant") return invalid();
    return { role: message.role, text: nonempty(message.text) };
  });
  if (messages.at(-1)?.role !== "user") return invalid();
  return { attemptId, consent: true, segments, messages };
}
export function parseManagedAskAnswer(value: unknown, segments: readonly { segmentId: string }[]): ManagedAskAnswer {
  const data = object(value, ["outcome", "text", "citationSegmentIds"]);
  if (!Array.isArray(data.citationSegmentIds)) return invalid();
  const ids = data.citationSegmentIds.map(nonempty);
  const sent = new Set(segments.map((segment) => segment.segmentId));
  if (new Set(ids).size !== ids.length || ids.some((id) => !sent.has(id))) return invalid();
  if (data.outcome === "supported" && ids.length) return { outcome: "supported", text: nonempty(data.text), citationSegmentIds: ids };
  if (data.outcome === "insufficient_evidence" && data.text === null && !ids.length) return { outcome: "insufficient_evidence", text: null, citationSegmentIds: [] };
  return invalid();
}

export const MANAGED_ASK_ANSWER_JSON_SCHEMA = {
  type: "object",
  properties: {
    outcome: { type: "string", enum: ["supported", "insufficient_evidence"] },
    text: { type: ["string", "null"] },
    citationSegmentIds: { type: "array", items: { type: "string" } },
  },
  required: ["outcome", "text", "citationSegmentIds"],
  additionalProperties: false,
} as const;
